# Generated by Django 5.2.8 on 2025-11-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('name',), 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
