# Generated by Django 5.2.8 on 2025-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
