# Generated by Django 5.2.8 on 2025-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(default=None, upload_to='file_book/'),
            preserve_default=False,
        ),
    ]
