# Generated by Django 5.2.8 on 2026-05-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_achievement_icon_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='code',
            field=models.CharField(db_index=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
