# Generated by Django 5.2.8 on 2026-02-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'verbose_name': 'Статус книги', 'verbose_name_plural': 'Статус книги'},
        ),
    ]
