# Generated by Django 5.2.8 on 2026-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_author_delete_authors_rename_books_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_place',
            field=models.TextField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
